"""add abstract column to paper_registry

Revision ID: 1828bd5b34ba
Revises: 78442285b63e
Create Date: 2026-07-30 15:28:48.601585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1828bd5b34ba'
down_revision: Union[str, None] = '78442285b63e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_registry', sa.Column('abstract', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_registry', 'abstract')
    # ### end Alembic commands ###
