"""create paper_registry, chunk_registry, session_history

Revision ID: 78442285b63e
Revises: 
Create Date: 2026-07-27 19:13:58.615438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78442285b63e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_registry',
    sa.Column('paper_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('arxiv_id', sa.String(length=32), nullable=True),
    sa.Column('doi', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('trust_tier', sa.String(length=20), server_default='unverified', nullable=True),
    sa.Column('ingestion_status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('raw_pdf_s3_path', sa.Text(), nullable=True),
    sa.Column('parsed_doc_s3_path', sa.Text(), nullable=True),
    sa.Column('citation_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('parent_citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("source_type IN ('local_corpus','arxiv_fetched','user_uploaded')", name='ck_paper_source_type'),
    sa.PrimaryKeyConstraint('paper_id'),
    sa.UniqueConstraint('arxiv_id')
    )
    op.create_table('session_history',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('route_taken', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('faithfulness_score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('chunk_registry',
    sa.Column('chunk_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=True),
    sa.Column('chunk_type', sa.String(length=20), nullable=True),
    sa.Column('section_name', sa.String(length=128), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('part_index', sa.Integer(), server_default='0', nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('vector_db_id', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_registry.paper_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_registry')
    op.drop_table('session_history')
    op.drop_table('paper_registry')
    # ### end Alembic commands ###
