"""Add artifact_path

Revision ID: d4f305cbf148
Revises: 1828bd5b34ba
Create Date: 2026-08-02 18:15:48.506181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f305cbf148'
down_revision: Union[str, None] = '1828bd5b34ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk_registry', sa.Column('artifact_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk_registry', 'artifact_path')
    # ### end Alembic commands ###
