"""Add mode and paper_id to sessions

Revision ID: d591f5ed0e1d
Revises: e48e0c5bd007
Create Date: 2026-08-03 19:38:35.454998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd591f5ed0e1d'
down_revision: Union[str, None] = 'e48e0c5bd007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('mode', sa.String(length=20), server_default='research', nullable=False))
    op.add_column('sessions', sa.Column('paper_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'paper_registry', ['paper_id'], ['paper_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'paper_id')
    op.drop_column('sessions', 'mode')
    # ### end Alembic commands ###
